-- Step 1 SQL/audit invariants: 50 SELECT-only checks
-- Replace namespace placeholders; no writes allowed.
SELECT 'EVS-01' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-02' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-03' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-04' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-05' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-06' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-07' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-08' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-09' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-10' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE) AS true_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-true-%';
SELECT 'EVS-11' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-12' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-13' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-14' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-15' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-16' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-17' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-18' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-19' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-20' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE) AS false_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-evidence-false-%';
SELECT 'EVS-21' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-22' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-23' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-24' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-25' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-26' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-27' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-28' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-29' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-30' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVS-31' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-32' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-33' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-34' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-35' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-36' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-37' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-38' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-39' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-40' AS invariant, COUNT(*) FILTER (WHERE vector_dims(embedding)=1536) AS embedded_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-%';
SELECT 'EVS-41' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
SELECT 'EVS-42' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
SELECT 'EVS-43' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
SELECT 'EVS-44' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
SELECT 'EVS-45' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
SELECT 'EVS-46' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
SELECT 'EVS-47' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
SELECT 'EVS-48' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
SELECT 'EVS-49' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
SELECT 'EVS-50' AS invariant, COUNT(*) AS non_target_mutation_suspects FROM memory_items WHERE updated_at > created_at AND idempotency_key LIKE 'store_memory:%:ev-%' AND category NOT LIKE 'ev_%';
