-- Step 2 SQL/audit invariants: 50 SELECT-only checks
-- Replace namespace placeholders; no writes allowed.
SELECT 'EVP-S-01' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-02' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-03' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-04' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-05' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-06' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-07' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-08' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-09' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-10' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-11' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-12' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-13' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-14' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-15' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS TRUE AND tier='long_term') AS promoted_by_ev FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-accept-%';
SELECT 'EVP-S-16' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-17' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-18' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-19' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-20' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-21' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-22' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-23' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-24' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-25' AS invariant, COUNT(*) FILTER (WHERE evidence_validated IS FALSE AND tier='recent') AS denied_false_signal FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-deny-false-%';
SELECT 'EVP-S-26' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-27' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-28' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-29' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-30' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-31' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-32' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-33' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-34' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-35' AS invariant, COUNT(*) AS duplicate_keys FROM (SELECT idempotency_key FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' GROUP BY idempotency_key HAVING COUNT(*) > 1) d;
SELECT 'EVP-S-36' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-37' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-38' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-39' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-40' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-41' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-42' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-43' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-44' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-45' AS invariant, COUNT(*) FILTER (WHERE tier='long_term' AND evidence_validated IS TRUE) AS accepted_rows FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%';
SELECT 'EVP-S-46' AS invariant, COUNT(*) AS unexpected_null_embedding FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' AND embedding IS NULL;
SELECT 'EVP-S-47' AS invariant, COUNT(*) AS unexpected_null_embedding FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' AND embedding IS NULL;
SELECT 'EVP-S-48' AS invariant, COUNT(*) AS unexpected_null_embedding FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' AND embedding IS NULL;
SELECT 'EVP-S-49' AS invariant, COUNT(*) AS unexpected_null_embedding FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' AND embedding IS NULL;
SELECT 'EVP-S-50' AS invariant, COUNT(*) AS unexpected_null_embedding FROM memory_items WHERE idempotency_key LIKE 'store_memory:%:ev-probe-%' AND embedding IS NULL;
